 'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),mode=require('../lib/runmode');
const tree='D:/HT9045/HT9011UC_Cpp_V3.33.906.0';
const base={request:'launch',program:'${workspaceFolder}/../Obj/V906/build_dbg/wb_serve.exe'};
const source=fs.readFileSync(path.join(root,'extension.js'),'utf8');
const vscode={debug:{},window:{setStatusBarMessage(){},showWarningMessage(s){throw Error(s);}}};
const fakeFs={readFileSync:()=>JSON.stringify({configurations:[base]})};
const ctx={vscode,path,fs:fakeFs,liveconfig:{stripJsonc:s=>s},setTimeout,console,require:p=>p==='./lib/runmode'?mode:require(p)};
vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('const RUN_DIRS ='),source.indexOf('\nclass CppNav'))+'\nthis.RunBar=RunBar;',ctx);
const bar=Object.create(ctx.RunBar.prototype);bar.plan=()=>({tree});bar.update=()=>{};bar.f5Build=()=>null;bar.sessions=new Set();bar.stopWaitMs=0;bar.curState=()=> 'running';
const mine=[true,false].flatMap(sim=>[true,false].map(debug=>({path:mode.resolve(base,tree,sim,debug).cfg.program,pid:100+(sim?10:0)+(debug?1:0)})));
const other={pid:900,path:'D:/Other/Obj/V906/build_f5_sim_release/wb_serve.exe'};
const sibling={pid:901,path:'D:/HT9045/Obj/V906/build_f5_sim_release/other.exe'};
assert.strictEqual(bar.treeProcs([...mine,other,sibling]).length,4);
for(const p of mine)assert(bar.inTree({configuration:{program:p.path}}));
assert(!bar.inTree({configuration:{program:other.path}}));
let alive=[mine[0],other],signalled=[];bar.procLister=()=>alive;
bar.signalQuit=async pids=>{signalled=pids;alive=alive.filter(p=>!pids.includes(p.pid));return pids;};
bar.spawn=()=>{throw Error('Normal close must not force kill');};
(async()=>{const result=await bar.stopAll();assert.deepStrictEqual(Array.from(signalled),[mine[0].pid]);assert.strictEqual(alive[0],other);assert.strictEqual(result.killed.length,0);assert.strictEqual(result.still.length,0);console.log('PASS: all four F5 modes recognized; unrelated programs excluded; stopAll sends normal quit to owned PID only.');})().catch(e=>{console.error(e);process.exitCode=1;});
