// ===========================================================================
//  AlarmCodeCatalog.h -- static alarm-code catalog of the BCB6 MDB Updater (SQLiteUpdater.exe), CSV version.
//
//  AI(W906-CSVONLY) 20260926: cMyDB plan P2 ("先做 D:\MDB Updater 裡面項目的轉換", user 20260926).
//    * AlarmCodeCatalog.cpp is GENERATED by tools/gen_alarmcode_catalog.py from
//      D:\MDB Updater\MDB_Updater_Rev902.0_20260410\CreatDatabase.cpp -- do not edit it by hand.
//    * AlarmCodeUpdater.cpp is hand-written: the CSV-only remainder of golden TfMain::UpdateAlarmList()
//      (MDB Updater Main.cpp:318-371) -- dedup like DoInsertAlarmCode (first wins, "@@Error!!" on a repeat),
//      save D:\HT9045\Error\AlarmCodeList.txt, save the update log under D:\HT9045_Log\MDB_UpdateLog\.
//    * Not carried over: every sqlite step (sqlite3 retired, user 20260926), DoSaveEventLog (DB only),
//      TraceDB (Tray.DB/Plate.DB -> CSV, deferred by the user).
//    * The user ruled "C++ 靜態表 and a shipped AlarmCodeList.txt, both": the shipped copy is
//      ship/Error/AlarmCodeList.txt, produced by the same generator from the same data.
//    * NOT WIRED into boot yet: cMyDB's MyDBUpdateDB() will consume this after the Tester-comm (GPIB) work
//      (user 20260926 ordering).
//
//  Standard C++ only (no vclcompat), so the unit builds and tests without the rest of the tree.
// ===========================================================================
#ifndef AlarmCodeCatalogH
#define AlarmCodeCatalogH

#include <cstddef>
#include <cstdio>
#include <string>
#include <vector>

// Called once per golden DoInsertAlarmCode(Code, Message), in golden order, BEFORE dedup.
typedef void (*AlarmCodeSink)(const char* code, const char* msg, void* ctx);

// Replays golden CreateTableAlarmList(): "WAR000000", then units 001..031, Unit 24 as the motor double loop.
void AlarmCodeCatalog_Replay(AlarmCodeSink sink, void* ctx);

// Length of the golden insertion sequence (before dedup).
std::size_t AlarmCodeCatalog_RawCount();

struct AlarmCodeListEntry
{
    std::string code;
    std::string message;
};

struct AlarmCodeUpdateResult
{
    std::size_t rawCount;                   // insertions attempted
    std::vector<AlarmCodeListEntry> list;   // after dedup, golden order ("CODE=Message" lines)
    std::vector<std::string> duplicates;    // codes rejected as repeats (first occurrence kept)
    bool listWritten;                       // AlarmCodeList.txt saved
    bool logWritten;                        // update log saved
    std::string logPath;
};

// Builds the deduplicated list only (no file I/O).
AlarmCodeUpdateResult AlarmCodeCatalog_Build();

// CSV-only golden UpdateAlarmList(): build, then write listPath ("CODE=Message\r\n" per line, like
// TStringList::SaveToFile) and a log file in logDir.  Empty listPath / logDir skips that file.
// versionLine is the first log line (golden writes VerInfo().GetFileVersion() there).
AlarmCodeUpdateResult AlarmCodeCatalog_UpdateList(const std::string& listPath,
                                                  const std::string& logDir,
                                                  const std::string& versionLine);

// Golden paths (MDB Updater Main.cpp:370, CreatDatabase.cpp:47).
extern const char* const kAlarmCodeListPath;     // "D:\\HT9045\\Error\\AlarmCodeList.txt"
extern const char* const kAlarmCodeUpdateLogDir;  // "D:\\HT9045_Log\\MDB_UpdateLog"

#endif
