# -*- coding: utf-8 -*-
r"""Check every deployed page wiring is still intact.

  python check_deployed.py              # exit 0 = all green, 1 = something drifted
  python check_deployed.py --selftest   # prove the checks can actually fail

`D:\HT9045\web` is git-ignored and the client package is synced BY HAND, so git
is not a safety net for any of this and drift is silent. This checks the four
invariants that actually bite:

  1. every wired page loads ht9045_recipe_client.js BEFORE its own script
     (the client defines HT9045Recipe; the order is load-bearing, and getting
     it wrong fails only at runtime, in the browser, with no build to catch it)
  2. every deployed js parses, and every js WE generate (tools/pagewire/wire) is
     byte-identical to the deployed copy (someone hand-edited the live file, or
     the deploy is stale)
  3. every deployed js is listed in OURS in BOTH sync_web.py copies -- a file
     missing from OURS is deleted by the next sync, and "deleted 0" then stops
     meaning anything
  4. (INFORMATIONAL since 20260924) pages that exist only in the client repo
     and not in web/page are LISTED, never failed

AI(W906-A6) 20260924 -- user ruling A6 (following P5 of 20260923, "web/page is
the ONLY authority"): invariants 2 and 4 used to compare web/page byte for byte
with the colleague's client repo.  That repo (D:\HT9045_Client, origin
ht9045_web.git) has had a single commit since 20260917 while web/page kept
moving, so 69 of those comparisons were permanently red: "web/page is newer"
reported as drift.  A check that is always red trains people to ignore red.
Now: pass-through js (not generated by us) only has to exist and parse;
invariant 4 only lists client-only pages (e.g. Main.gbControlBtn.html, the
State Record button page) so they can be pulled in deliberately, one at a time.

The page list is DISCOVERED, not hardcoded: any page referencing a
ht9045_*.js of ours is picked up, so this needs no editing when a page is added.

**--selftest exists because a check that has never been seen to fail is not a
check.** It builds a fixture where each invariant is deliberately violated and
asserts every one is caught -- through the same code path the real run uses,
not a reimplementation of it.
"""
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile

CLIENT_LIB = "ht9045_recipe_client.js"
# our scripts, but never the library itself -- it is the dependency, not a page
# AI(W906-NL-SCOPE) 20260916: 樣式原本只認舊命名 `ht9045_<name>_wire.js`。
# 20260915 的引擎架構（commit 8a379ca「部署引擎架構到 14 頁」）把部署的接線
# 腳本改成 `ht9045_wire_<name>.js`，樣式沒跟著改，於是 **14 頁靜默掉出守備
# 範圍**，而這支工具照樣印 ALL GREEN。
#
# 實測（20260916 03:05，`D:\HT9045\web\page`）：
#     舊樣式罩住 1 頁（只剩 main，靠 home_refresh 命中）
#     新樣式罩住 15 頁，涉及 17 支 js
#
# 兩代命名都要認：舊的檔案還在樹上，selftest 的 fixture 也用舊命名。
OURS_RE = re.compile(
    r'src\s*=\s*"(ht9045_(?:\w+_wire|wire_\w+|home_refresh)\.js)"')

# AI(W906-WIRE-SYS) 20260917：三個 D:\HT9045_Client\ 重指到專屬 web repo。
#   那個資料夾是我們留的**過期快照**（Steven 0915 那版）。他 0917 已經把
#   HT9045_Client\ 併進 D:\HT9045\ 本體（他的 CHANGES §1.5），權威來源改成
#   https://gitlab.honprec.com/honprec/rd/rd5/ht9045_web.git 的 checkout。
#
#   ⚠ 這不是「順手更新路徑」——它就是第 3 項紅燈的根因。檢查報「OURS 少了
#     12 支接線檔」，實測他**現在**那份 sync_web.py 12 支全列（33 筆），
#     過期快照只有 30 筆。紅的是我們指錯地方，不是他沒做。
#     先量再改，否則就會去改他的檔 —— 那會製造真正的分岔。
# AI(W906-SENTINEL-PATH) 20260924：ht9045_web repo 的 checkout 不一定在 D:\HT9045_web。
#   20260922 佈署的新筆電把它放在 D:\HT9045_Client（git remote＝ht9045_web.git）；那台上 D:\HT9045_web 不存在，
#   這支哨兵於是 95 項全紅（20260924 02:0x 實測），紅的是路徑不是接線。
#   ⚠ 不能只看資料夾在不在：舊筆電上的 D:\HT9045_Client 是上面那段說的「過期快照」。所以依序：
#     環境變數 HT9045_WEB_REPO → D:\HT9045_web → **origin 是 ht9045_web.git 的** D:\HT9045_Client。
def _web_repo():
    cands = [os.environ.get("HT9045_WEB_REPO"), r"D:\HT9045_web", r"D:\HT9045_Client"]
    for c in cands:
        if not c or not os.path.isdir(os.path.join(c, "web", "page")):
            continue
        if c.rstrip("\\/").lower().endswith("ht9045_client"):
            try:
                url = subprocess.run(["git", "-C", c, "remote", "get-url", "origin"],
                                     capture_output=True, text=True, timeout=30).stdout
            except Exception:
                url = ""
            if "ht9045_web" not in url:
                continue
        return c
    return r"D:\HT9045_web"


_WEB_REPO = _web_repo()
REAL = {
    "web": r"D:\HT9045\web\page",
    "client_web": os.path.join(_WEB_REPO, "web", "page"),
    "client_js": os.path.join(_WEB_REPO, "client"),
    # AI(W906-WIRE-SYS) 20260917：我們產生的那一份（merge_all.py 的落點）。
    #   部署到 web/page 的接線檔多數是**這裡**來的，不是他的 client/ 直接複製。
    "generated": r"D:\HT9045\HT9011UC_Cpp_V3.33.906.0\tools\pagewire\wire",
    "syncs": [r"D:\HT9045\HT9011UC_Cpp_V3.33.906.0\tools\websync\sync_web.py",
              os.path.join(_WEB_REPO, "tools", "sync_web.py")],   # AI(W906-SENTINEL-PATH) 20260924：同上
}


def rd(p):
    return io.open(p, "rb").read()


def discover(web):
    """{page stem: [js, ...]} -- EVERY script of ours the page loads.

    AI(W906-NL-SCOPE) 20260916: 原本回傳 `m.group(1)`，也就是**第一個**命中。
    引擎架構下一頁會載三支（`recipe_client` / `wire_engine` / `wire_<page>`），
    只取第一個等於**每頁只檢查 wire_engine**，14 支 per-page 接線腳本
    連 `node --check` 都沒跑到。回傳整串才對得起「守住接線」這句話。
    """
    out = {}
    if not os.path.isdir(web):
        return out
    for name in sorted(os.listdir(web)):
        if not name.lower().endswith(".html"):
            continue
        hits = OURS_RE.findall(io.open(os.path.join(web, name), encoding="utf-8",
                                       errors="replace").read())
        if hits:
            out[name[:-5]] = sorted(set(hits))
    return out


def run(cfg, quiet=False):
    """Returns the list of failure strings. Empty list = all green."""
    fails = []

    def bad(msg):
        fails.append(msg)
        if not quiet:
            print("  FAIL  " + msg)

    def ok(msg):
        if not quiet:
            print("  ok    " + msg)

    web, cweb, cjs = cfg["web"], cfg["client_web"], cfg["client_js"]
    # AI(W906-WIRE-SYS) 20260917：從 cfg 拿，**不要**讀全域 REAL ——
    #   selftest 傳的是暫存 fixture，讀全域會讓自我測試被真實的樹影響。
    gen = cfg.get("generated") or ""
    pages = discover(web)
    if not pages:
        bad("no wired pages found under %s -- is the path right?" % web)
        return fails
    if not quiet:
        print("discovered %d wired page(s)\n" % len(pages))
        print("=== 1. script order inside each deployed page ===")
    for stem, jss in sorted(pages.items()):
        txt = io.open(os.path.join(web, stem + ".html"), encoding="utf-8",
                      errors="replace").read()
        # AI(W906-WIRE-SYS) 20260917：鎖在 src="..." 裡，不要用裸檔名。
        #   txt.find(js) 會命中**註解裡的「提到」**。實測 4 頁中招：
        #     HW.IoSetView.html:627 與 main.html:298 的註解 -> 假陽性（該綠報紅）；
        #     Setup.Contact.html / Setup.HotPlate.html 的註解提到 CLIENT_LIB，
        #     把 i_lib 拉到檔案更前面 -> **假陰性**（該紅變綠）。
        #   假陽性會被人判掉，假陰性沒有人會來找。
        def at(name):
            return txt.find('src="%s"' % name)
        i_lib = at(CLIENT_LIB)
        for js in jss:
            i_own = at(js)
            if i_lib < 0:
                bad("%s.html references %s but never loads %s"
                    % (stem, js, CLIENT_LIB))
            elif i_lib > i_own:
                bad("%s.html loads %s AFTER %s -- order is load-bearing"
                    % (stem, CLIENT_LIB, js))
            else:
                ok("%-22s client then %s" % (stem, js))

    if not quiet:
        print("\n=== 2. each js parses, and matches ITS OWN authoritative source ===")
    for js in sorted({j for v in pages.values() for j in v} | {CLIENT_LIB}):
        a, b = os.path.join(web, js), os.path.join(cjs, js)
        if not os.path.isfile(a):
            bad("%s missing from web/page" % js)
            continue
        if subprocess.call(["node", "--check", a], stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, shell=True) != 0:
            bad("%s does not parse (node --check)" % js)
        # AI(W906-WIRE-SYS) 20260917：跟**各自的權威來源**比。
        #   接線檔多數是 merge_wire.py 產生的（對本機 64 個工單與實體 ini
        #   重新分類過），跟他的 client/ 來源本來就不同 —— 一律比 client/
        #   會讓 17 支恆紅，而恆紅的檢查等於沒有檢查。
        #   但不能直接刪：這一項真正要守的是「有人手改了線上檔」。
        g = os.path.join(gen, js) if gen else ""
        if os.path.isfile(g):
            if rd(a) != rd(g):
                bad("%s differs between web/page and our generated wire/ "
                    "-- someone hand-edited the deployed copy, or the deploy is stale" % js)
            else:
                ok("%-30s parses, web == generated (%d bytes)" % (js, len(rd(a))))
        else:
            # AI(W906-A6) 20260924：原樣通過的檔（不是我們產生的）以 web/page 為準（P5），
            #   不再拿凍結在 0917 的 client repo 比 —— 那個比較恆紅，等於沒有檢查。
            #   只要求它存在（上面）而且能解析（上面的 node --check）。
            ok("%-30s parses (pass-through; web/page is the authority) (%d bytes)" % (js, len(rd(a))))

    if not quiet:
        print("\n=== 3. OURS lists every deployed js, in BOTH sync_web.py copies ===")
    want = sorted({j for v in pages.values() for j in v} | {CLIENT_LIB})
    for sp in cfg["syncs"]:
        if not os.path.isfile(sp):
            bad("sync file missing: %s" % sp)
            continue
        txt = io.open(sp, encoding="utf-8", errors="replace").read()
        miss = [js for js in want if ("page/" + js) not in txt]
        if miss:
            bad("%s: OURS is missing %s -- the next sync deletes it"
                % (os.path.basename(sp), ", ".join(miss)))
        else:
            ok("%-46s all %d listed" % (os.path.basename(sp), len(want)))

    if not quiet:
        print("\n=== 4. (informational) pages only in the client repo, not in web/page ===")
        # AI(W906-A6) 20260924：只列不判。要搬哪一頁由人決定（例：做 State Record 按鈕時才搬
        #   Main.gbControlBtn.html），不整批同步。
        only = []
        if os.path.isdir(cweb):
            only = sorted(n for n in os.listdir(cweb)
                          if n.lower().endswith(".html") and not os.path.isfile(os.path.join(web, n)))
        print("  info  %d page(s) exist only in the client repo%s"
              % (len(only), (": " + ", ".join(only[:12]) + (" ..." if len(only) > 12 else "")) if only else ""))
    return fails


# --------------------------------------------------------------------- selftest
GOOD_PAGE = ('<html><body>\n<p>x</p>\n'
             '<script src="ht9045_recipe_client.js"></script>\n'
             '<script src="ht9045_%s_wire.js"></script>\n</body></html>\n')
GOOD_JS = "(function(){ 'use strict'; })();\n"


def build_fixture(root, break_what):
    web = os.path.join(root, "web"); cweb = os.path.join(root, "cweb")
    cjs = os.path.join(root, "cjs"); syncdir = os.path.join(root, "sync")
    gen = os.path.join(root, "gen")   # AI(W906-WIRE-SYS) 20260917: 我們產生的那一份
    for d in (web, cweb, cjs, syncdir, gen):
        os.makedirs(d)
    js = "ht9045_alpha_wire.js"
    page = GOOD_PAGE % "alpha"
    if break_what == "order":
        page = page.replace(
            '<script src="ht9045_recipe_client.js"></script>\n'
            '<script src="%s"></script>\n' % js,
            '<script src="%s"></script>\n'
            '<script src="ht9045_recipe_client.js"></script>\n' % js)
    io.open(os.path.join(web, "Alpha.html"), "w", newline="").write(page)
    io.open(os.path.join(cweb, "Alpha.html"), "w", newline="").write(
        page if break_what != "page_drift" else page.replace("<p>x</p>", "<p>y</p>"))
    for name in (js, CLIENT_LIB):
        body = GOOD_JS
        if break_what == "parse" and name == js:
            body = "(function(){ this is not javascript\n"
        io.open(os.path.join(web, name), "w", newline="").write(body)
        io.open(os.path.join(cjs, name), "w", newline="").write(
            body if not (break_what == "js_drift" and name == js)
            else body + "// drifted\n")
        # AI(W906-WIRE-SYS) 20260917：gen_drift 專用 —— 只有這個案例才把檔案
        #   放進 generated/，這樣其他案例仍走「原樣通過」那條分支（維持原語意）。
        if break_what == "gen_drift" and name == js:
            io.open(os.path.join(gen, name), "w", newline="").write(
                body + "// generated differs from what is deployed\n")
    listed = [CLIENT_LIB] + ([] if break_what == "ours" else [js])
    sp = os.path.join(syncdir, "sync_web.py")
    io.open(sp, "w", newline="").write(
        "OURS = {\n" + "".join('    "page/%s",\n' % n for n in listed) + "}\n")
    return {"web": web, "client_web": cweb, "client_js": cjs, "syncs": [sp],
            "generated": gen}


def selftest():
    # AI(W906-A6) 20260924：js_drift／page_drift 兩個情境拿掉 —— 「和 client repo 不同」
    #   已經不是違規（使用者裁決 A6，web/page 是唯一權威）。其餘四個違規照舊必須被抓到。
    cases = [("(nothing broken)", 0), ("order", 1), ("parse", 1),
             ("gen_drift", 1), ("ours", 1)]
    bad = 0
    print("selftest -- each case builds a fixture and runs the REAL checks\n")
    for what, expect_min in cases:
        root = tempfile.mkdtemp(prefix="pagewire_selftest_")
        try:
            cfg = build_fixture(root, None if expect_min == 0 else what)
            fails = run(cfg, quiet=True)
            got = len(fails)
            hit = (got == 0) if expect_min == 0 else (got >= 1)
            print("  %-4s %-18s -> %d failure(s)%s"
                  % ("PASS" if hit else "FAIL", what, got,
                     "" if not fails else "  | " + fails[0][:74]))
            if not hit:
                bad += 1
        finally:
            shutil.rmtree(root, ignore_errors=True)
    print("\n%s" % ("selftest OK: every check can fail, and passes when nothing is broken"
                    if not bad else "SELFTEST FAILED on %d case(s)" % bad))
    return 1 if bad else 0


def main(argv):
    if "--selftest" in argv:
        return selftest()
    fails = run(REAL)
    print("\n%s" % ("ALL GREEN" if not fails else "%d PROBLEM(S)" % len(fails)))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
