'use strict';
// AI(W906-HTDESIGNER) 20260930: 自動接線 -- a C++ event handler the designer adds is reached from the web page
// with nothing left to do by hand (EastSun 20260930: "如果我有需要新增事件 其他連結 理應外掛程式自動幫我新增";
// "你用json中間連線的 是你這邊要幫我處理 我只需要處理C++的部分"). The chain, like WPF / BCB6's .dfm wiring:
//
//   page   <script id="htdEvents">  htdCpp('spbSave', 'mouseup', 'TfHotPlate', 'spbSaveMouseUp', 'OnMouseUp');
//            -> the page's WS client: rawCmd('htd.event', { tag: <page>, value: '{"form","handler",...}' })
//   server the dispatch branch of htd.event, the same shape as form.event's (one branch, on form.event's line)
//            -> <prefix>HtdEvent(tag, value, &ack, &err)
//   C++    HtdEvents/HtdEvents.gen.cpp (this module writes it): the table of the designer's events -> the form's
//            global object -> fHotPlate->spbSaveMouseUp(sender, button, shift, x, y)
//
// The same rules as form.event: not while the machine runs, under the same form lock. These functions only compute
// text and where it goes. Plain Node.
//
// AI(W906-HTDESIGNER) 20261001 (EastSun: "你這邊建置時 可能有問題"): the build may never see half of it. 08:46 an
// event added in the designer left CMakeLists.txt naming HtdEvents.gen.cpp while that file was still an unsaved
// untitled document -- the build failed. Now the extension writes the build's part (this generated file, the
// server's htd.event branch, the CMake entry) to disk at once, the generated file first; only the form's .h / .cpp
// and the page stay unsaved (Ctrl+Z). And every row of the generated table calls its handler only when the class
// HAS it (a compile-time test): a form .h / .cpp not saved yet, a handler renamed or undone -- it still compiles,
// and the web gets "no-handler" until the form is saved and rebuilt.

const { mask, classBody } = require('./cppstub');

const CMD = 'htd.event';
const GEN_REL = 'HtdEvents/HtdEvents.gen.cpp';
const TAG = 'AI(W906-HTDESIGNER)';

function eolOf(text) { return /\r\n/.test(String(text || '')) ? '\r\n' : '\n'; }
function lineStart(t, i) { while (i > 0 && t[i - 1] !== '\n') i--; return i; }
function lineEnd(t, i) { const n = t.indexOf('\n', i); return n < 0 ? t.length : (t[n - 1] === '\r' ? n - 1 : n); }

/**
 * The server's dispatch: a branch for htd.event made from form.event's (its checks, its call, its CompleteCommand,
 * with the names changed), put in front of it ON THE SAME LINE (the file's rule: 接在同一行，不移動行號).
 * -> { has: true } (already there) | { edit: { s, e, text }, fn } | { error }
 */
function serverHook(text, stamp) {
  const t = String(text || '');
  if (/\.cmd\s*==\s*"htd\.event"/.test(t)) {
    const f = /extern\s+bool\s+(\w*HtdEvent)\s*\(/.exec(t);
    return { has: true, fn: f ? f[1] : 'HtdEvent' };
  }
  const head = /\}\s*else\s+if\s*\(\s*(\w+)\.cmd\s*==\s*"form\.event"\s*\)\s*\{/.exec(t);
  if (!head) return { error: '伺服器程式裡找不到 form.event 的分派（} else if (x.cmd == "form.event") {）' };
  const s = head.index;
  const le = lineEnd(t, s);
  const next = new RegExp('\\}\\s*else\\s+if\\s*\\(\\s*' + head[1] + '\\.cmd\\s*==', 'g');
  next.lastIndex = s + head[0].length;
  const nx = next.exec(t);
  const e = nx && nx.index < le ? nx.index : le;
  let branch = t.slice(s, e);
  const fe = /extern\s+bool\s+(\w*?)FormEvent\s*\(/.exec(branch);
  if (!fe) return { error: 'form.event 的分派裡找不到 extern bool …FormEvent(…) 的宣告' };
  const fn = fe[1] + 'HtdEvent';
  branch = branch.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/\/\/.*$/, '')
    // (form.event's own follow-ups -- `{ extern void W906_FormEventRunAfterAck(bool ok); W906_FormEventRunAfterAck(feOk); }`
    //  (1003): what form.event's handlers queued -- are not htd.event's: left out)
    .replace(new RegExp('\\{\\s*extern\\s+\\w+\\s+(' + fe[1] + 'FormEvent\\w+)\\s*\\([^)]*\\)\\s*;\\s*\\1\\s*\\([^)]*\\)\\s*;\\s*\\}', 'g'), ' ')
    .replace(/form\.event/g, 'htd.event')
    .replace(new RegExp('\\b' + fe[1] + 'FormEvent\\b', 'g'), fn)
    .replace(/[ \t]{2,}/g, ' ').replace(/\s+$/, '');
  if (!branch.includes(fn + '(') || !/CompleteCommand\s*\(/.test(branch)) return { error: 'form.event 的分派形狀認不得（沒有呼叫與 CompleteCommand）' };
  // (another form.event-only call it does not know: not copied over by guess)
  const left = /\b\w*FormEvent\w*/.exec(branch);
  if (left) return { error: 'form.event 的分派裡有認不得的 form.event 專用呼叫（' + left[0] + '）：沒有自動加 htd.event 分支，請手動接' };
  // (ASCII only: the extension puts it into the file byte by byte -- the server's file is not all valid UTF-8, and a
  //  save through a UTF-8 editor would change the bytes it cannot read)
  const note = '/*' + TAG + ' ' + stamp + ': the designer\'s events (web -> the C++ form\'s event handlers), form.event\'s checks; body ' + GEN_REL + ' (generated by the designer); same line, no line moves*/';
  const open = branch.indexOf('{');
  const text2 = branch.slice(0, open + 1) + ' ' + note + branch.slice(open + 1) + ' ';
  return { edit: { s, e: s, text: text2 }, fn };
}

/**
 * CMake: the server executable's source list gets the generated file, in front of its closing parenthesis (same line).
 * `serverRel`: the server's source as the list names it (tools/wb_serve.cpp). -> { has } | { edit } | { error }
 */
function cmakeHook(text, serverRel, genRel) {
  const t = String(text || '');
  const rel = genRel || GEN_REL;
  const re = /add_executable\s*\(/g;
  let m;
  while ((m = re.exec(t))) {
    // the call's closing parenthesis: # comments and "strings" skipped, $<...> / nested parentheses counted
    let depth = 1, i = m.index + m[0].length, q = false;
    for (; i < t.length && depth; i++) {
      const c = t[i];
      if (q) { if (c === '\\') { i++; continue; } if (c === '"') q = false; continue; }
      if (c === '"') { q = true; continue; }
      if (c === '#') { const n = t.indexOf('\n', i); i = n < 0 ? t.length : n; continue; }
      if (c === '(') depth++;
      else if (c === ')') depth--;
    }
    if (depth) break;
    const close = i - 1;
    const call = t.slice(m.index, close);
    const code = call.replace(/#[^\n]*/g, '');
    if (!new RegExp('(^|[\\s(])' + serverRel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '(\\s|$)').test(code)) continue;
    // 1006: the generated code is several files (genParts) -- the main one listed here, the parts by a glob (a part comes and
    // goes with its form's events; CONFIGURE_DEPENDS = a new / removed one is seen at the next build, no re-configure by hand)
    const hasMain = code.includes(rel), hasParts = /\bHTD_GEN_PARTS\b/.test(t);
    if (hasMain && hasParts) return { has: true };
    const nl = /\r\n/.test(t) ? '\r\n' : '\n';
    const ls = lineStart(t, m.index), indent = t.slice(ls, m.index).replace(/\S.*$/, '');
    const glob = hasParts ? '' : 'file(GLOB HTD_GEN_PARTS CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/' + PART_DIR + '/*.gen.cpp")   # ' + TAG + ': the designer\'s generated event calls, one file per form header' + nl + indent;
    const tail = (hasMain ? '' : '  ' + rel) + (hasParts ? '' : '  ${HTD_GEN_PARTS}');
    return { edit: { s: m.index, e: close, text: glob + t.slice(m.index, close) + tail } };
  }
  return { error: 'CMakeLists.txt 裡找不到列出 ' + serverRel + ' 的 add_executable' };
}

/** The designer's events in the generated file: [{ form, handler, control, event }]. */
/**
 * 1009 event-wiring walkthrough #4: each row read from a table remembers that table's text (not enumerable -- not copied,
 * not compared, not serialised): the write checks the table on disk is still that text (another window wrote it meanwhile
 * = refused, not overwritten with an old snapshot).
 */
const SRC = Symbol('htdGenSrc');
function rowsOf(genText) {
  const out = [];
  const src = String(genText || '');
  const re = /^\/\/\s*htd-row\s+(\w+)\s+(\w+)\s+(\S+)\s+(On\w+)\s*$/gm;   // (1009 review (gen #11): a control id with "-" too)
  let m;
  while ((m = re.exec(src))) { const row = { form: m[1], handler: m[2], control: m[3], event: m[4] }; Object.defineProperty(row, SRC, { value: src }); out.push(row); }
  return out;
}
/** The table text the rows were read from (the first that has one), or undefined. */
function srcOf(rows) {
  for (const r of rows || []) if (r && typeof r[SRC] === 'string') return r[SRC];
  return undefined;
}

/** The class's global object: `extern TfHotPlate *fHotPlate;` in its .h, else `TfHotPlate *fHotPlate = ...` in its .cpp. */
function globalOf(hText, cppText, cls) {
  const mh = mask(hText || '');
  // (1009 review (gen #8): "extern PACKAGE TfAdam6024 *fAdam6024;" too -- 111 of 184 forms had no global and could not be wired)
  const h = new RegExp('\\bextern\\s+(?:PACKAGE\\s+)?' + cls + '\\s*\\*\\s*(\\w+)\\s*;').exec(mh);
  if (h) return h[1];
  // (1009 review (gen #1): "#define fPadInterface (W906_PadInterfaceObject())" -- the macro is the object)
  const want = cls.replace(/^Tf/, 'f');
  if (want !== cls && new RegExp('^[ \\t]*#[ \\t]*define[ \\t]+' + want + '\\b', 'm').test(mh)) return want;
  // (1009 review (gen #1): in the .cpp only a definition at file scope -- "    TfPadInterface* p=fPadInterface;" inside a
  //  function was taken for it: the generated part called p, which did not exist, and wb_serve no longer built. A
  //  static one or one inside a namespace is not reachable from the generated file either: none, and not wired)
  const mc = mask(cppText || '');
  const re = new RegExp('^[ \\t]*' + cls + '\\s*\\*\\s*(\\w+)\\s*=', 'gm');
  let c;
  while ((c = re.exec(mc))) {
    let depth = 0;
    for (let i = 0; i < c.index; i++) { const ch = mc.charCodeAt(i); if (ch === 123) depth++; else if (ch === 125) depth--; }
    if (depth !== 0) continue;
    const ls = mc.lastIndexOf('\n', c.index - 1) + 1;
    if (/\bstatic\b/.test(mc.slice(ls, c.index + c[0].length))) continue;
    return c[1];
  }
  return null;
}

/** public / private / protected at `off` inside the class body (a class starts private). */
function accessAt(maskedText, body, off) {
  const seg = maskedText.slice(body.open + 1, off);
  // (1009 review (gen #12): the class's own labels only -- a nested struct's "public:" made a private handler after it look
  //  public; the generated call then quietly answered no-handler)
  let flat = '', depth = 0;
  for (const ch of seg) { if (ch === '{') depth++; else if (ch === '}') depth = Math.max(0, depth - 1); else if (depth === 0) { flat += ch; continue; } flat += ' '; }
  const re = /\b(public|private|protected)\s*:/g;
  let a = 'private', m;
  while ((m = re.exec(flat))) a = m[1];
  return a;
}

/** The handler's declaration in the class: { params, access } or null. */
function declOf(hText, cls, name) {
  const b = classBody(hText, cls);
  if (!b) return null;
  const m = mask(hText);
  const re = new RegExp('\\bvoid\\s+(?:__fastcall\\s+)?' + name + '\\s*\\(([^)]*)\\)\\s*;', 'g');   // (1009 review (gen #7): void __fastcall X(...) too)
  re.lastIndex = b.open;
  const x = re.exec(m);
  if (!x || x.index > b.close) return null;
  return { params: hText.slice(x.index, x.index + x[0].length).replace(/^[^(]*\(/, '').replace(/\)\s*;$/, '').replace(/\s+/g, ' ').trim(), access: accessAt(m, b, x.index) };
}

/** The class's `void name(params);` declarations: [{ name, params, access }] (the value list of the Events tab). */
function methodsOf(hText, cls) {
  const b = classBody(hText, cls);
  if (!b) return [];
  const m = mask(hText);
  const re = /\bvoid\s+(?:__fastcall\s+)?(\w+)\s*\(([^)]*)\)\s*;/g;
  re.lastIndex = b.open;
  const out = [];
  let x;
  while ((x = re.exec(m)) && x.index < b.close) {
    const params = hText.slice(x.index, x.index + x[0].length).replace(/^[^(]*\(/, '').replace(/\)\s*;$/, '').replace(/\s+/g, ' ').trim();
    out.push({ name: x[1], params, access: accessAt(m, b, x.index) });
  }
  return out;
}

/** The parameter types only ("TObject*,TMouseButton,TShiftState,int,int"): "a compatible method signature". */
function typesKey(params) {
  return String(params || '').split(',').map(p => p.replace(/\s*([*&])\s*/g, '$1 ').replace(/\s+/g, ' ').trim())
    .filter(Boolean).map(p => p.replace(/^const /, '').replace(/ ?\w+$/, '').replace(/\s+/g, '')).join(',');
}

/** Does the class have the control as a member (`TSpeedButton *spbSave ...`)? */
function hasMember(hText, cls, ctl) {
  const b = classBody(hText, cls);
  if (!b || !ctl) return false;
  // (1009 review (gen #6 / #11): "TPanel *a, *b, *c;" (fLotInfo.h has 34 such lines) and "TButton* b{nullptr};" -- only the last
  //  of a line was found, the others' Sender went as nullptr; the id escaped)
  return new RegExp('\\*\\s*' + String(ctl).replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*[=;,\\[{]').test(mask(hText).slice(b.open, b.close));
}

/**
 * The call of `obj->name(...)` made from what the page sends (a.button / a.x / a.y / a.shift ... a.key / a.chr),
 * by the declared parameters. -> { pre: [statements], call, args, dargs, usesShift } | { error }
 * dargs: the arguments for the compile-time test (decltype): a local of `pre` there is std::declval<its type&>().
 */
function callOf(params, obj, name, sender) {
  const ps = String(params || '').split(',').map(s => s.trim()).filter(Boolean);
  const pre = [], args = [], dargs = [];
  let usesShift = false, n = 0;
  for (const p of ps) {
    // "TObject *Sender" / "WORD &Key" / "TShiftState Shift" / "unsigned short &Key" / "int X"
    const m = /^(?:const )?([\w:]+(?: [\w:]+)*?) ?([*&]?) ?(\w+)?$/.exec(p.replace(/\s*([*&])\s*/g, ' $1 ').replace(/\s+/g, ' ').trim());
    if (!m) return { error: '參數「' + p + '」認不得' };
    const type = m[1], ref = m[2] || '', pname = m[3] || '';
    const len = args.length;
    if (type === 'TObject' && ref === '*') args.push(sender);
    else if (type === 'TMouseButton' && !ref) { args.push('HtdButton(a)'); usesShift = true; }
    else if (type === 'TShiftState' && !ref) { args.push('HtdShift(a)'); usesShift = true; }
    // (1009 review (gen #3): only X / Y come from the page -- OnSelectCell's ACol / ARow went as 0, 0: every click selected
    //  the first cell)
    else if (type === 'int' && !ref && /^[XY]$/i.test(pname)) args.push(/^X$/i.test(pname) ? 'a.x' : 'a.y');
    else if (type === 'int' && !ref) return { error: '參數「' + p + '」網頁給不出來（網頁事件只有滑鼠的 X／Y）' };
    else if ((type === 'WORD' || type === 'Word' || type === 'unsigned short') && ref === '&') { const v = 'k' + (n++); pre.push(type + ' ' + v + ' = (' + type + ')a.key;'); args.push(v); dargs.push('std::declval<' + type + '&>()'); }
    else if (type === 'char' && ref === '&') { const v = 'c' + (n++); pre.push('char ' + v + ' = (char)a.chr;'); args.push(v); dargs.push('std::declval<char&>()'); }
    else if (type === 'bool' && ref === '&') { const v = 'b' + (n++); pre.push('bool ' + v + ' = true;'); args.push(v); dargs.push('std::declval<bool&>()'); }
    else return { error: '參數「' + p + '」網頁給不出來（網頁事件只有滑鼠按鍵、位置、Shift／Ctrl／Alt、按鍵碼）' };
    if (dargs.length === len) dargs.push(args[len]);
  }
  return { pre, call: obj + '->' + name + '(' + args.join(', ') + ');', args, dargs, usesShift };
}

/**
 * 1009 review (gen #4): a row's run function named by what it is -- form, handler, control, event (+ a short hash of
 * them, so "btn-a" / "btn_a" cannot meet). By its place in the table (HtdGenRun0, 1 ...) a part file left over from
 * before (a write that failed half way, a build reading between the writes) defined the number another row now has:
 * it linked, and TfB's button ran TfA's handler. Now a mismatch is a link error, never the wrong handler.
 */
function runName(r) {
  const key = [r.form, r.handler, r.control, r.event].join('|');
  let h = 5381;
  for (let i = 0; i < key.length; i++) h = ((h * 33) ^ key.charCodeAt(i)) >>> 0;
  const w = x => String(x || '').replace(/[^A-Za-z0-9_]/g, '_');
  return 'HtdGenRun_' + w(r.form) + '_' + w(r.handler) + '_' + w(r.control) + '_' + w(r.event) + '_' + h.toString(16);
}

function esc(s) { return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }

/**
 * An edit computed on a file's text read as latin1 (one char = one byte, so the offsets are byte offsets), put into
 * its bytes: every other byte stays as it was -- a file that is not all valid UTF-8 (the server's) is not re-encoded.
 * The inserted text must be latin1 (what came from the same file, plus ASCII). -> Buffer | null
 */
function spliceBytes(buf, edit) {
  if (!buf || !edit || /[^\x00-\xff]/.test(edit.text)) return null;
  return Buffer.concat([buf.slice(0, edit.s), Buffer.from(edit.text, 'latin1'), buf.slice(edit.e)]);
}

/**
 * The generated C++ file. rows: [{ form, handler, control, event, header, call: { pre, call } }];
 * ctx: { fn, cjson, lockHeader, lock, unlock, running: [names], shiftHeader }. One edit writes it whole.
 */
function genFile(rows, ctx, eol) {
  const E = eol || '\n';
  const c = ctx || {};
  const L = [];
  L.push('// 產生檔 -- HTML 視覺設計工具（tools/vscode-htdesigner）。不要手改：在設計工具的事件表新增、改名，它會重寫這個檔。');
  L.push('// ---------------------------------------------------------------------------');
  L.push('//  WS 命令 ' + CMD + '：網頁上的事件 → C++ 表單類別的事件函式（像 BCB6 的 .dfm 把 OnClick 接到 spbSaveClick）。');
  L.push('//  網頁（<script id="htdEvents"> 的 htdCpp(...)）送 value＝{"form","handler","control","event",');
  L.push('//  "button","x","y","shift","ctrl","alt","dbl","key","chr"}（tag＝頁名）；這裡照表找到那一列，在表單的全域物件上呼叫它。');
  L.push('//  跟 form.event 一樣：' + (c.running && c.running.length ? '機台運轉中（' + c.running.join('／') + '）不跑、' : '') +
    (c.lock ? '持 ' + c.lock.replace(/^.*::/, '') + '（同一把鎖）。' : '（這棵樹沒有找到表單鎖）。'));
  L.push('//  伺服器的分派：' + CMD + ' 那一個分支（設計工具加在 form.event 的同一行）。');
  L.push('//  事件（一列一個，設計工具靠這幾行重寫這個檔）：');
  for (const r of rows) L.push('// htd-row ' + r.form + ' ' + r.handler + ' ' + r.control + ' ' + r.event);
  L.push('// ---------------------------------------------------------------------------');
  L.push('#include <exception>');
  L.push('#include <string>');
  L.push('#include <type_traits>');
  L.push('#include <utility>');
  L.push('');
  if (c.cjson) L.push('#include "' + c.cjson + '"');
  if (c.lockHeader) L.push('#include "' + c.lockHeader + '"');
  const usesShift = rows.some(r => r.call && r.call.usesShift);
  // (split, 1006: no form header here -- each one's calls are in HtdEvents/part/<header>.gen.cpp, see genParts)
  if (c.split) L.push('#include "HtdEvents.gen.h"');
  if (!c.split && usesShift && c.shiftHeader) L.push('#include "' + c.shiftHeader + '"');
  const hs = [];
  if (!c.split) for (const r of rows) if (r.header && !hs.includes(r.header)) hs.push(r.header);
  for (const h of hs) L.push('#include "' + h + '"');
  L.push('');
  for (const v of c.running || []) L.push('extern bool ' + v + ';');
  if ((c.running || []).length) L.push('');
  const IN = c.split ? 'HtdGenIn' : 'HtdIn';
  if (c.split) { rows.forEach((r, i) => L.push('int ' + runName(r) + '(const HtdGenIn& a);   // ' + r.form + '::' + r.handler + ' -- ' + partRelOf(r.header))); L.push(''); }
  L.push('namespace {');
  L.push('');
  if (!c.split) {
  L.push('struct HtdIn { int button = 0; int x = 0; int y = 0; bool shift = false; bool ctrl = false; bool alt = false; bool dbl = false; int key = 0; int chr = 0; };');
  L.push('');
  L.push('// Sender：表單有那個元件就傳它（VCL 的 Sender），沒有就 nullptr');
  L.push('template <class T> TObject* HtdSender(T* p, typename std::enable_if<std::is_convertible<T*, TObject*>::value>::type* = 0) { return p; }');
  L.push('template <class T> TObject* HtdSender(T*, typename std::enable_if<!std::is_convertible<T*, TObject*>::value>::type* = 0) { return nullptr; }');
  if (usesShift) {
    L.push('TShiftState HtdShift(const HtdIn& a) { TShiftState s; if (a.shift) s << ssShift; if (a.alt) s << ssAlt; if (a.ctrl) s << ssCtrl; if (a.dbl) s << ssDouble; return s; }');
    L.push('TMouseButton HtdButton(const HtdIn& a) { return a.button == 2 ? mbRight : a.button == 1 ? mbMiddle : mbLeft; }');
  }
  L.push('');
  // a row calls its handler only when the class has it as the generator saw it (C<i>(..., int) is chosen then);
  // else the (..., long) one: it still compiles -- a form .h not saved yet, a handler renamed / undone -- and says 0
  if (rows.length) {
    L.push('// 1 = run; 0 = the class has no such handler (its .h / .cpp not saved yet, renamed or removed); -1 = the form object is null');
  }
  rows.forEach((r, i) => {
    const c = r.call || {};
    const obj = r.obj || (/^(\w+)->/.exec(c.call || '') || [])[1] || 'nullptr';
    const onO = s => String(s).replace(new RegExp('\\b' + obj + '->', 'g'), 'o->');
    const args = (c.args || []).map(onO), dargs = (c.dargs || c.args || []).map(onO);
    const pre = (c.pre || []).join(' ') + (c.pre && c.pre.length ? ' ' : '');
    L.push('// ' + r.form + '::' + r.handler + '（' + r.control + '.' + r.event + '）');
    L.push('template <class T> auto C' + i + '(T* o, const HtdIn& a, int) -> decltype((void)o->' + r.handler + '(' + dargs.join(', ') + '), 1) { (void)a; if (!o) return -1; ' +
      pre + 'o->' + r.handler + '(' + args.join(', ') + '); return 1; }');
    L.push('template <class T> int C' + i + '(T*, const HtdIn&, long) { return 0; }');
    L.push('int E' + i + '(const HtdIn& a) { return C' + i + '(' + obj + ', a, 0); }');
  });
  L.push('');
  }
  L.push('struct HtdRow { const char* form; const char* handler; const char* control; const char* event; int (*run)(const ' + IN + '&); };');
  L.push('const HtdRow kRows[] = {');
  rows.forEach((r, i) => L.push('    {"' + r.form + '", "' + r.handler + '", "' + r.control + '", "' + r.event + '", &' + (c.split ? runName(r) : 'E' + i) + '},'));
  L.push('    {nullptr, nullptr, nullptr, nullptr, nullptr},');
  L.push('};');
  L.push('');
  L.push('std::string Str(const cJSON* o, const char* k) { const cJSON* v = cJSON_GetObjectItemCaseSensitive(o, k); return v && cJSON_IsString(v) && v->valuestring ? std::string(v->valuestring) : std::string(); }');
  L.push('int Int(const cJSON* o, const char* k) { const cJSON* v = cJSON_GetObjectItemCaseSensitive(o, k); return v && cJSON_IsNumber(v) ? (int)v->valuedouble : 0; }');
  L.push('bool Bool(const cJSON* o, const char* k) { const cJSON* v = cJSON_GetObjectItemCaseSensitive(o, k); return v && cJSON_IsTrue(v); }');
  L.push('');
  L.push('}  // namespace');
  L.push('');
  L.push('bool ' + c.fn + '(const std::string& tag, const std::string& valueJson, std::string* ack, std::string* err)');
  L.push('{');
  L.push('    (void)tag;');
  if ((c.running || []).length) {
    L.push('    if (' + c.running.join(' || ') + ') {');
    L.push('        *err = "running: 機台運轉中不能從網頁執行畫面的事件（同 form.event）";');
    L.push('        return false;');
    L.push('    }');
  }
  L.push('    cJSON* root = cJSON_Parse(valueJson.c_str());');
  L.push('    if (!root || !cJSON_IsObject(root)) {');
  L.push('        if (root) cJSON_Delete(root);');
  L.push('        *err = "bad-payload: value must be a JSON object string {\\"form\\",\\"handler\\",\\"control\\",\\"event\\",...}";');
  L.push('        return false;');
  L.push('    }');
  L.push('    const std::string form = Str(root, "form"), handler = Str(root, "handler"), control = Str(root, "control");');
  L.push('    ' + IN + ' a;');
  L.push('    a.button = Int(root, "button"); a.x = Int(root, "x"); a.y = Int(root, "y");');
  L.push('    a.shift = Bool(root, "shift"); a.ctrl = Bool(root, "ctrl"); a.alt = Bool(root, "alt"); a.dbl = Bool(root, "dbl");');
  L.push('    a.key = Int(root, "key"); a.chr = Int(root, "chr");');
  L.push('    cJSON_Delete(root);');
  L.push('    const HtdRow* r = nullptr;');
  L.push('    // (the same handler may serve several controls: the row of this control first, for its Sender)');
  L.push('    for (const HtdRow* p = kRows; p->form; ++p) if (form == p->form && handler == p->handler && control == p->control) { r = p; break; }');
  L.push('    if (!r) for (const HtdRow* p = kRows; p->form; ++p) if (form == p->form && handler == p->handler) { r = p; break; }');
  L.push('    if (!r) {');
  L.push('        *err = "unknown-handler: " + form + "::" + handler + " is not in ' + esc(GEN_REL) + ' (add it in the designer\'s events table)";');
  L.push('        return false;');
  L.push('    }');
  L.push('    int ran = 0;');
  L.push('    std::string why;');
  if (c.lock) L.push('    ' + c.lock + '();');
  L.push('    try {');
  L.push('        ran = r->run(a);');
  L.push('    } catch (const std::exception& x) {');
  L.push('        ran = -2; why = std::string("exception: ") + x.what();');
  L.push('    } catch (...) {');
  L.push('        ran = -2; why = "non-std exception";');
  L.push('    }');
  if (c.unlock) L.push('    ' + c.unlock + '();');
  L.push('    if (ran == -2) { *err = "handler-failed: " + why; return false; }');
  L.push('    if (ran == 0) { *err = std::string("no-handler: ") + r->form + "::" + r->handler + " is not in the class this server was built with (the form\'s .h / .cpp not saved, or renamed / removed) -- save them and rebuild"; return false; }');
  L.push('    if (ran < 0) { *err = std::string("no-form: the form object of ") + r->form + " is null"; return false; }');
  L.push('    *ack = std::string("{\\"form\\":\\"") + r->form + "\\",\\"handler\\":\\"" + r->handler + "\\",\\"control\\":\\"" + r->control + "\\",\\"event\\":\\"" + r->event + "\\"}";');
  L.push('    return true;');
  L.push('}');
  L.push('');
  return L.join(E);
}

/**
 * 1006 (the enumeration -- every page's events, built: one generated file including every form's header broke as soon as
 * TfLtcSensor's acarry_shims.h met the forms that include Public/HTEditList.h -- both define class TList / uPlateInfo):
 * the generated code in several translation units --
 *   GEN_REL                         the table and the dispatch (no form header at all)
 *   HtdEvents/HtdEvents.gen.h       the value read from the page (shared)
 *   HtdEvents/part/<header>.gen.cpp each form header's rows' calls, that header alone
 * -> [{ rel, text }] (the main file first). CMake takes the parts with a glob (cmakeHook).
 */
const GEN_H_REL = 'HtdEvents/HtdEvents.gen.h';
const PART_DIR = 'HtdEvents/part';
function partRelOf(header) { return PART_DIR + '/' + String(header || 'noheader').replace(/\.h(pp)?$/i, '').replace(/[^A-Za-z0-9]+/g, '_') + '.gen.cpp'; }
function genParts(rows, ctx, eol) {
  const E = eol || '\n';
  const c = ctx || {};
  const out = [];
  // -- the shared header
  out.push({ rel: GEN_H_REL, text: [
    '// 產生檔 -- HTML 視覺設計工具（tools/vscode-htdesigner）。不要手改。',
    '// 網頁送來的值（' + GEN_REL + ' 讀、HtdEvents/part/*.gen.cpp 用）。',
    '#pragma once',
    'struct HtdGenIn { int button = 0; int x = 0; int y = 0; bool shift = false; bool ctrl = false; bool alt = false; bool dbl = false; int key = 0; int chr = 0; };',
    ''].join(E) });
  // -- one part per header
  const byHeader = new Map();
  rows.forEach((r, i) => { const h = r.header || ''; if (!byHeader.has(h)) byHeader.set(h, []); byHeader.get(h).push({ r, i }); });
  for (const [h, list] of byHeader) {
    const usesShift = list.some(x => x.r.call && x.r.call.usesShift);
    const L = [];
    L.push('// 產生檔 -- HTML 視覺設計工具。不要手改：' + (h || '（沒有表頭）') + ' 這個表單的事件呼叫（只 include 它自己的 .h：');
    L.push('// 不同表單的 .h 放在同一個檔裡會互相衝突，所以一個表頭一個檔）。表在 ' + GEN_REL + '。');
    L.push('#include <type_traits>');
    L.push('#include "../HtdEvents.gen.h"');
    if (usesShift && c.shiftHeader) L.push('#include "' + c.shiftHeader + '"');
    if (h) L.push('#include "' + h + '"');
    else if (c.lockHeader) L.push('#include "' + c.lockHeader + '"');   // (no header known: TObject from the form lock's)
    L.push('');
    L.push('namespace {');
    L.push('template <class T> TObject* HtdSender(T* p, typename std::enable_if<std::is_convertible<T*, TObject*>::value>::type* = 0) { return p; }');
    L.push('template <class T> TObject* HtdSender(T*, typename std::enable_if<!std::is_convertible<T*, TObject*>::value>::type* = 0) { return nullptr; }');
    if (usesShift) {
      L.push('TShiftState HtdShift(const HtdGenIn& a) { TShiftState s; if (a.shift) s << ssShift; if (a.alt) s << ssAlt; if (a.ctrl) s << ssCtrl; if (a.dbl) s << ssDouble; return s; }');
      L.push('TMouseButton HtdButton(const HtdGenIn& a) { return a.button == 2 ? mbRight : a.button == 1 ? mbMiddle : mbLeft; }');
    }
    L.push('// 1 = run; 0 = the class has no such handler (its .h / .cpp not saved yet, renamed or removed); -1 = the form object is null');
    for (const { r, i } of list) {
      const cc = r.call || {};
      const obj = r.obj || (/^(\w+)->/.exec(cc.call || '') || [])[1] || 'nullptr';
      const onO = s => String(s).replace(new RegExp('\\b' + obj + '->', 'g'), 'o->');
      const args = (cc.args || []).map(onO), dargs = (cc.dargs || cc.args || []).map(onO);
      const pre = (cc.pre || []).join(' ') + (cc.pre && cc.pre.length ? ' ' : '');
      L.push('// ' + r.form + '::' + r.handler + '（' + r.control + '.' + r.event + '）');
      L.push('template <class T> auto C' + i + '(T* o, const HtdGenIn& a, int) -> decltype((void)o->' + r.handler + '(' + dargs.join(', ') + '), 1) { (void)a; if (!o) return -1; ' +
        pre + 'o->' + r.handler + '(' + args.join(', ') + '); return 1; }');
      L.push('template <class T> int C' + i + '(T*, const HtdGenIn&, long) { return 0; }');
    }
    L.push('}  // namespace');
    L.push('');
    for (const { r, i } of list) L.push('int ' + runName(r) + '(const HtdGenIn& a) { return C' + i + '(' + (r.obj || (/^(\w+)->/.exec((r.call || {}).call || '') || [])[1] || 'nullptr') + ', a, 0); }');
    L.push('');
    out.push({ rel: partRelOf(h), text: L.join(E) });
  }
  // -- the table and the dispatch: genFile's, with the calls in the parts
  out.unshift({ rel: GEN_REL, text: genFile(rows, Object.assign({}, c, { split: true }), E) });
  return out;
}

module.exports = { SRC, srcOf, runName, CMD, GEN_REL, GEN_H_REL, PART_DIR, partRelOf, serverHook, cmakeHook, rowsOf, globalOf, declOf, methodsOf, typesKey, hasMember, callOf, genFile, genParts, accessAt, spliceBytes };
