/* ht9045_wire_hwhandlersys.js -- HW.HandlerSys.html 的接線資料（行為在 ht9045_wire_engine.js）
 * ---------------------------------------------------------------------------
 * //Steven 20260916  （這個檔是產生的；標記由 gen_wire.py 的樣板寫入，重跑後仍在）
 * 當日完整變更紀錄：D:\docs\ChangeLog\CHANGES_20260916_Steven.md
 * ---------------------------------------------------------------------------
 * AI(W906-FW-GEN) 20260914：由 scratchpad/gen_wire.py 從 golden 機械產生。
 * 手改這個檔會在下次重跑產生器時被覆蓋 —— 要改請改產生器或 golden。
 *
 * 來源表單    HandlerSys.dfm
 * 抽取法      WriteIniData / WriteIniDataGeneral / WriteIniDataNoLog
 *             （widget 與區段/鍵同一行）＋ HTEditList 一跳法，
 *             全部限定在該表單自己的 .cpp，不做全樹 id 反查。
 *             目標檔由呼叫的第 1 個參數解析（General 家族固定 Gerneral.ini），
 *             不假設「一頁一個檔」—— uteach 同一表單就寫兩個檔。
 * 小鍵盤      golden ShowQwertyKey(Sender, N_FLAGS, dp, checkRange, min, max)
 *             配上 .dfm 的 OnMouseDown = <handler>。
 *
 * 機台設定檔（/api/system/）gerneral
 *   文字欄位     33 個（逐鍵比對過實檔確認存在）
 *   非文字控制項 181 個（radio group / checkbox / combo）
 * 必接 0 個（該鍵在所有擁有該文件的配方裡都存在）
 * 選用 0 個（部分配方才有；讀取時缺了不算錯，存檔時自動略過）
 * 未接 0 個（見檔尾 PENDING —— 這些鍵在任何配方檔裡都不存在，抽取有誤）
 * 小鍵盤 30 個欄位有 golden 依據
 * ⚠ 其中 8 個的 golden 範圍是負值或 max<=0。golden 的
 *   myQwertyKeyBoard.cpp:252 會把那種範圍整組換成 0~65535，
 *   用在負值欄位上會把輸入夾成 0。本檔一律關掉那些夾限，
 *   欄位仍可輸入，只是少一道範圍檢查。
 */
HT9045Wire.register({
  page: 'HW.HandlerSys.html',
  slug: 'hwhandlersys',
  fields: {
  },
  sysFields: {
    ed24VMonitorPulseCount:        ['gerneral', 'System', 'I24V_PULSE_COUNT'],
    edATCSystemIP:                 ['gerneral', 'ATC', 'ATC_SYSTEM_IP'],
    edATCSystemPort:               ['gerneral', 'ATC', 'ATC_SYSTEM_PORT'],
    edATCSystemUseHeat:            ['gerneral', 'ATC', 'ATC_SYSTEM_USEHEAT'],
    edCognexSystemCCD:             ['gerneral', '2D_BarCode', 'BAR_CODE_USECOUNT'],
    edGroundMan_AlarmOhm:          ['gerneral', 'Ground_Man', 'Ground_Man_AlarmOhm'],
    edHotGunFlow_DevNo:            ['gerneral', 'System', 'HotGunFlow_DevNo'],
    edHotGunFlow_Gun1_ChannelNo:   ['gerneral', 'System', 'HotGunFlow_Gun1_ChannelNo'],
    edHotGunFlow_Gun2_ChannelNo:   ['gerneral', 'System', 'HotGunFlow_Gun2_ChannelNo'],
    edHotGunFlow_LineNo:           ['gerneral', 'System', 'HotGunFlow_LineNo'],
    edIONPulseCount:               ['gerneral', 'System', 'ION_PULSE_COUNT'],
    edMaxKpa:                      ['gerneral', 'System', 'EP_MAXKPA'],
    edMaxMpaFB:                    ['gerneral', 'System', 'EP_MAXA'],
    edMinMpa:                      ['gerneral', 'System', 'EP_MINMPA'],
    edtBaseMaxTemp:                ['gerneral', 'System', 'SetHeaterTemp_MaxBase'],
    edtCustomerCode:               ['gerneral', 'System', 'CUSTOMER_CODE'],
    edtHPLimit:                    ['gerneral', 'System', 'BASE_X_TO_HP'],
    edtIndexMaxTemp:               ['gerneral', 'System', 'SetHeaterTemp_MaxIndex'],
    edtMaxXPitch:                  ['gerneral', 'System', 'IN_OUT_ARM_X_PITCH_MAX'],
    edtMaxYPitch:                  ['gerneral', 'System', 'IN_OUT_ARM_Y_PITCH_MAX'],
    edtMinMpaFB:                   ['gerneral', 'System', 'EP_MINA_FeedBack'],
    edtMinXPitch:                  ['gerneral', 'System', 'IN_OUT_ARM_X_PITCH_MIN'],
    edtMinYPitch:                  ['gerneral', 'System', 'IN_OUT_ARM_Y_PITCH_MIN'],
    edtOutShtMaxTemp:              ['gerneral', 'System', 'SetHeaterTemp_MaxOutSht'],
    edtOutSortXPitchMax:           ['gerneral', 'OutSortArm', 'USE_OUT_SORT_X_PITCH_MAX'],
    edtOutSortXPitchMin:           ['gerneral', 'OutSortArm', 'USE_OUT_SORT_X_PITCH_MIN'],
    edtSeriaNo:                    ['gerneral', 'Version', 'Serial No'],
    edtTriTempTotalCh:             ['gerneral', 'System', 'TriTemperature_TotalChannel'],
    edtTriTemperature_MaxDegree:   ['gerneral', 'System', 'Tri_Temperature_MaxDegree'],
    edtTriTemperature_MinDegree:   ['gerneral', 'System', 'Tri_Temperature_MinDegree'],
    edtUserDefMaxContactHeight:    ['gerneral', 'Index', 'UserDefMaxContactHeight'],
    edtUserDefineIndexZSafePos:    ['gerneral', 'Index', 'UserDefineIndexZSafePos'],
    edt_Total_Compressor:          ['gerneral', 'System', 'Total_Compressor'],
  },
  sysEnums: {
    ArmZAtoZH:                     ['gerneral', 'System', 'INOUT_ARM_PICKER_USE_MOTOR', 'index'],
    Auto2SelectCy:                 ['gerneral', 'System', 'bUseAuto2Empty', 'index'],
    ElectronPressure:              ['gerneral', 'System', 'EP_Install', 'index'],
    MachineTrack:                  ['gerneral', 'System', 'AUTO_EMPTY_COLOR', 'index'],
    cbAuto1Cassette:               ['gerneral', 'TrayCassette', 'AUTO1_USE_Cassette', 'bool'],
    cbAuto2Cassette:               ['gerneral', 'TrayCassette', 'AUTO2_USE_Cassette', 'bool'],
    cbAuto3Cassette:               ['gerneral', 'TrayCassette', 'AUTO3_USE_Cassette', 'bool'],
    cbAuto4Cassette:               ['gerneral', 'TrayCassette', 'AUTO4_USE_Cassette', 'bool'],
    cbAuto5Cassette:               ['gerneral', 'TrayCassette', 'AUTO5_USE_Cassette', 'bool'],
    cbAuto6Cassette:               ['gerneral', 'TrayCassette', 'AUTO6_USE_Cassette', 'bool'],
    cbColorCassette:               ['gerneral', 'TrayCassette', 'COLOR_USE_Cassette', 'bool'],
    cbColorSenAmpCnt:              ['gerneral', 'System', 'ColorSenAmpQty', 'index'],
    cbESDUse4COM:                  ['gerneral', 'EM Aware', 'EM_AWARE_USE_4_COM', 'bool'],
    cbEmptyCassette:               ['gerneral', 'TrayCassette', 'EMPTY_USE_Cassette', 'bool'],
    cbEnableOutShtSensor:          ['gerneral', 'System', 'ENABLE_OUT_SHUTTLE_SENEOR', 'bool'],
    cbLoaderCassette:              ['gerneral', 'TrayCassette', 'LOAD_USE_Cassette', 'bool'],
    cbRotateSenAmpCnt:             ['gerneral', 'System', 'RotateSenAmpQty', 'index'],
    cbSocketSenAmpCnt:             ['gerneral', 'System', 'SocketSenAmpQty', 'index'],
    cbSocketSenAmpCnt2nd:          ['gerneral', 'System', 'SocketSenAmpQty2nd', 'index'],
    cbSocketSenAmpCnt3rd:          ['gerneral', 'System', 'SocketSenAmpQty3rd', 'index'],
    cbVibrationCardQty:            ['gerneral', 'System', 'VibrationCardQty', 'index'],
    chk2x3modeUseAxisYSensor:      ['gerneral', 'System', 'Use_AxisY_Sensor_2x3mode', 'bool'],
    chkAuto1:                      ['gerneral', 'TrayZ', 'AUTO1_Z_USE_MOTOR', 'bool'],
    chkAuto1Y:                     ['gerneral', 'TrayY', 'AUTO1_Y_USE_MOTOR', 'bool'],
    chkAuto2:                      ['gerneral', 'TrayZ', 'AUTO2_Z_USE_MOTOR', 'bool'],
    chkAuto2Y:                     ['gerneral', 'TrayY', 'AUTO2_Y_USE_MOTOR', 'bool'],
    chkAuto3:                      ['gerneral', 'TrayZ', 'AUTO3_Z_USE_MOTOR', 'bool'],
    chkAuto3Y:                     ['gerneral', 'TrayY', 'AUTO3_Y_USE_MOTOR', 'bool'],
    chkAuto4:                      ['gerneral', 'TrayZ', 'AUTO4_Z_USE_MOTOR', 'bool'],
    chkAuto5:                      ['gerneral', 'TrayZ', 'AUTO5_Z_USE_MOTOR', 'bool'],
    chkAuto6:                      ['gerneral', 'TrayZ', 'AUTO6_Z_USE_MOTOR', 'bool'],
    chkBiasModeUseYSensor:         ['gerneral', 'System', 'Bias_Mode_Use_Y_Sensor', 'bool'],
    chkColor:                      ['gerneral', 'TrayZ', 'COLOR_Z_USE_MOTOR', 'bool'],
    chkColorY:                     ['gerneral', 'TrayY', 'COLOR_Y_USE_MOTOR', 'bool'],
    chkEmpty:                      ['gerneral', 'TrayZ', 'EMPTY_Z_USE_MOTOR', 'bool'],
    chkEmptyY:                     ['gerneral', 'TrayY', 'EMPTY_Y_USE_MOTOR', 'bool'],
    chkLoader:                     ['gerneral', 'TrayZ', 'LOAD_Z_USE_MOTOR', 'bool'],
    chkLoaderY:                    ['gerneral', 'TrayY', 'LOAD_Y_USE_MOTOR', 'bool'],
    chkOutShtYSensorByLatch:       ['gerneral', 'System', 'ENABLE_OUT_SHUTTLEY_LATCH', 'bool'],
    chkUseHPComCard:               ['gerneral', 'IndexDriver', 'USE_HP_COM_CARD', 'bool'],
    chkUserDefMaxContactHeight:    ['gerneral', 'Index', 'EnableUserDefMaxContactHeight', 'bool'],
    chkUser_Define_IndexZ_SafePos: ['gerneral', 'Index', 'EnableUser_Define_IndexZ_SafePos', 'bool'],
    coCanBusNudn1:                 ['gerneral', 'System', 'CanBusNudn1Qty', 'index'],
    coNudn1Macid11:                ['gerneral', 'System', 'Nudn1Macid11Qty', 'index'],
    coNudn1Macid12:                ['gerneral', 'System', 'Nudn1Macid12Qty', 'index'],
    coNudn1Macid13:                ['gerneral', 'System', 'Nudn1Macid13Qty', 'index'],
    coNudn1Macid14:                ['gerneral', 'System', 'Nudn1Macid14Qty', 'index'],
    rg2DBarcode:                   ['gerneral', '2D_BarCode', 'BAR_CODE_INSTALL', 'index'],
    rg2ndLoader:                   ['gerneral', 'System', 'USE_2nd_LOADER', 'index'],
    rg3M_EM_AWARE_Monitor:         ['gerneral', 'System', 'USE_ESD_Monior', 'index'],
    rgAOI:                         ['gerneral', 'System', 'AOI', 'index'],
    rgATC:                         ['gerneral', 'ATC', 'USE_ATC_MODE', 'index'],
    rgATCHeatGun:                  ['gerneral', 'System', 'INSTALL_ATC_HEAT_GUN', 'index'],
    rgATCMixMode:                  ['gerneral', 'ATC', 'ATC_Mix_Mode', 'index'],
    rgAirConditioner:              ['gerneral', 'AIR_CON', 'USE_AIR_CONDITIONER', 'index'],
    rgAirStreamSelect:             ['gerneral', 'System', 'AirStream_Select', 'index'],
    rgAuto3Magazine:               ['gerneral', 'System', 'AUTO3_IS_MAGAZINE', 'index'],
    rgAutoAlignment:               ['gerneral', 'System', 'USE_AUTO_ALIGNMENT', 'index'],
    rgAutoCleanIonFan:             ['gerneral', 'System', 'USE_AutoCleanIonFan', 'index'],
    rgAutoShuttleSensor:           ['gerneral', 'System', 'AUTO_SENSOR_INSTALL', 'index'],
    rgAutoTrackCanGoRear:          ['gerneral', 'System', 'bAutoTrackCanGoRear', 'index'],
    rgBaseHeaterCount:             ['gerneral', 'System', 'BASE_HEATER_COUNT', 'index'],
    rgBottom2DID:                  ['gerneral', '2D_BarCode', 'BOTTOM_2DID', 'index'],
    rgBottom2DID_CCD:              ['gerneral', '2D_BarCode', 'BOTTOM_2DID_CCD', 'index'],
    rgCCDAutoAlignmentMode:        ['gerneral', 'System', 'MACHINE_HAS_AUTO_ALIGNMENT_CCD', 'index'],
    rgCCDTemp:                     ['gerneral', 'System', 'CCD2_TEMPER', 'index'],
    rgCKDFCM:                      ['gerneral', 'System', 'USE_CKD_FCM_CleanAir', 'index'],
    rgCOLORSENSOR_MUN:             ['gerneral', 'System', 'USE_COLORSENSOR_MUN', 'index'],
    rgCanBusMethod:                ['gerneral', 'System', 'Canbus_Method', 'index'],
    rgCatchTrayBlock:              ['gerneral', 'System', 'UseCatchTrayBlock', 'index'],
    rgCatchTrayModel:              ['gerneral', 'System', 'USE_CATCH_TRAY_MODEL', 'index'],
    rgChamberUsePulseType:         ['gerneral', 'System', 'CHAMBER_USE_PULSE_TYPE', 'index'],
    rgCleanAir:                    ['gerneral', 'IndexDriver', 'CLEAN_AIR', 'index'],
    rgColorSensor:                 ['gerneral', 'System', 'USE_COLOR_TRAY_SENSOR', 'index'],
    rgCoverTrayID:                 ['gerneral', 'System', 'USE_COVER_TRAYID', 'index'],
    rgDeviceFlipper:               ['gerneral', 'System', 'USE_DEVICE_FLIPPER', 'index'],
    rgDewpointHW:                  ['gerneral', 'System', 'DewPoint_Hardware_Install', 'index'],
    rgDieClean:                    ['gerneral', 'System', 'USE_DIE_CLEAN', 'index'],
    rgDoubleBeltMode:              ['gerneral', 'System', 'DOUBLE_BELT_MODE', 'index'],
    rgDoubleEPControl:             ['gerneral', 'System', 'INSTALL_DOUBLE_EP', 'index'],
    rgE84Sensor:                   ['gerneral', 'System', 'AGVModal', 'index'],
    rgESDTemp:                     ['gerneral', 'System', 'Index_ESDAir', 'index'],
    rgEmptyKeyence:                ['gerneral', 'System', 'USE_KEYENCE_EMPTY', 'index'],
    rgFinePitch:                   ['gerneral', 'System', 'USE_FINE_PITCH', 'index'],
    rgFix3FullPlace:               ['gerneral', 'System', 'FIX3_FULL_PLACE', 'index'],
    rgFixAICCD:                    ['gerneral', 'System', 'Fix_AI_CCD', 'index'],
    rgGroundMan:                   ['gerneral', 'Ground_Man', 'USE_GROUND_MAN', 'index'],
    rgGroundMan_ScanPoint:         ['gerneral', 'Ground_Man', 'Ground_Man_ScanPoint', 'index'],
    rgHTIonBar:                    ['gerneral', 'System', 'HTIonBarFunction', 'index'],
    rgHeatGun:                     ['gerneral', 'System', 'INSTALL_HEAT_GUN', 'index'],
    rgHeater:                      ['gerneral', 'System', 'USE_16_HEATER', 'index'],
    rgHeaterType:                  ['gerneral', 'TempCtrl', 'HEATER_CTRL_TYPE', 'index'],
    rgHighTempLimit:               ['gerneral', 'System', 'HighTempLimit', 'index'],
    rgHotGunFlow:                  ['gerneral', 'System', 'HotGunFlowEnable', 'index'],
    rgHotPlateLimit:               ['gerneral', 'System', 'HOT_PLATE_LIMITATION', 'index'],
    rgHotPlatePos:                 ['gerneral', 'System', 'HOT_PLATE_POSITION', 'index'],
    rgHotplateType:                ['gerneral', 'System', 'USE_HOTPLATE_TYPE', 'index'],
    rgIOCard:                      ['gerneral', 'System', 'IO_CARD_TYPE', 'index'],
    rgIOChangeToque:               ['gerneral', 'IndexDriver', 'USE_IO_CHANGE_TOQUE', 'index'],
    rgInOutArmXPitch:              ['gerneral', 'System', 'USE_IN_OUT_ARM_X_PITCH', 'index'],
    rgInOutArmYPitch:              ['gerneral', 'System', 'USE_IN_OUT_ARM_Y_PITCH', 'index'],
    rgInShtAutoLatch:              ['gerneral', 'System', 'In_Shuttle_Auto_Latch', 'index'],
    rgInShtLastSensor:             ['gerneral', 'System', 'IN_SHT_LAST_SENSOR', 'index'],
    rgIndexMotionCard:             ['gerneral', 'System', 'INDEX_MOTION_CARD', 'index'],
    rgIndexMotorAxis:              ['gerneral', 'IndexDriver', 'USE_INDEX_ARM_AXES', 'index'],
    rgIndexMotorType:              ['gerneral', 'IndexDriver', 'INDEX_DRIVER_TYPE', 'index'],
    rgIndexPressType:              ['gerneral', 'System', 'INDEX_PRESS_TYPE', 'index'],
    rgIndexSuckerType:             ['gerneral', 'System', 'INDEX_SUCKER_TYPE', 'index'],
    rgInstallARTtwocylinder:       ['gerneral', 'System', 'bAutoZNoUseART', 'index'],
    rgInstallFix3:                 ['gerneral', 'System', 'FIX3_INSTALL', 'index'],
    rgIonFanType:                  ['gerneral', 'System', 'ION_FAN_TYPE', 'index'],
    rgKasuga:                      ['gerneral', 'System', 'USE_KASUGA', 'index'],
    rgKasuga_Fan:                  ['gerneral', 'System', 'USE_KASUGA_Fan', 'index'],
    rgLBTemp:                      ['gerneral', 'System', 'LB_TEMP', 'index'],
    rgLBTemp2:                     ['gerneral', 'System', 'LB_TEMP_UpDown', 'index'],
    rgLDCarRotAtm:                 ['gerneral', 'System', 'USE_LD_Rot_Arm', 'index'],
    rgLaserDistance:               ['gerneral', 'System', 'USE_LASER_DISTANCE', 'index'],
    rgLdUldCassetteMode:           ['gerneral', 'System', 'USE_LdUldCassetteMode', 'index'],
    rgLdUldUseStepMotor:           ['gerneral', 'TrayY', 'LoaderUnload_StepMotor', 'index'],
    rgLoaderHinge:                 ['gerneral', 'System', 'USE_LOADER_HINGE', 'index'],
    rgLoaderKeyence:               ['gerneral', 'System', 'USE_KEYENCE_LOADER', 'index'],
    rgLoaderVibration:             ['gerneral', 'System', 'LOADER_VIBRATION', 'index'],
    rgMNetSpeed:                   ['gerneral', 'System', 'MOTIONNET_SPEED', 'index'],
    rgMRSystem:                    ['gerneral', 'System', 'USE_MR_SYSTEM', 'index'],
    rgMagBinDispType:              ['gerneral', 'System', 'MAGAZINE_BIN_DISP_TYPE', 'index'],
    rgMagneticScale:               ['gerneral', 'System', 'USE_MAGNETIC_SCALE', 'index'],
    rgModel:                       ['gerneral', 'Version', 'SubModel', 'index'],
    rgMotionCard:                  ['gerneral', 'System', 'MOTION_CARD_TYPE', 'index'],
    rgMultileEmpty:                ['gerneral', 'System', 'USE_Multile_Empty', 'index'],
    rgMultileEmptyTrayIDKeyence:   ['gerneral', 'System', 'USE_MultileEmptyTrayID_Keyence', 'index'],
    rgNUECType:                    ['gerneral', 'System', 'NUEC_TYPE', 'index'],
    rgNovx3360:                    ['gerneral', 'System', 'USE_NOVX3360', 'index'],
    rgNumberPanelType:             ['gerneral', 'System', 'NUMBER_PANEL_TYPE', 'index'],
    rgOCR:                         ['gerneral', 'System', 'INSTALL_OCR', 'index'],
    rgOCRYStepMot:                 ['gerneral', 'System', 'INSTALL_OCR_YMot', 'index'],
    rgOHTSystem:                   ['gerneral', 'System', 'USE_OHT_SYSTEM', 'index'],
    rgOTDInstall:                  ['gerneral', 'System', 'USE_OTD', 'index'],
    rgOutArmYPitch:                ['gerneral', 'System', 'USE_OUT_ARM_Y_PITCH', 'index'],
    rgOutSortArm:                  ['gerneral', 'OutSortArm', 'USE_OUT_SORT_ARM', 'index'],
    rgPickerCount:                 ['gerneral', 'System', 'USE_PICKER_COUNT', 'index'],
    rgPreciser:                    ['gerneral', 'System', 'USE_PRECISER', 'index'],
    rgPreciserPos:                 ['gerneral', 'System', 'iPreciserInstallArea', 'index'],
    rgRFIDReader:                  ['gerneral', 'System', 'USE_RFID_READER', 'index'],
    rgRFIDSystem:                  ['gerneral', 'System', 'USE_RFID_SYSTEM', 'index'],
    rgRealTimeCCD:                 ['gerneral', 'System', 'REAL_TIME_CCD', 'index'],
    rgRealTimeCCDTempNum:          ['gerneral', 'System', 'RTC_TemperNumber', 'index'],
    rgRotateKit:                   ['gerneral', 'ROTATE_KIT', 'USE_ROTATE_KIT', 'index'],
    rgRotateKitIn:                 ['gerneral', 'ROTATE_KIT', 'iRotate_In_Index', 'index'],
    rgRotateKitOut:                ['gerneral', 'ROTATE_KIT', 'iRotate_Out_Index', 'index'],
    rgRotateKit_Type:              ['gerneral', 'ROTATE_KIT', 'RotateKit_Type', 'index'],
    rgSafeDoor:                    ['gerneral', 'System', 'SAFE_DOOR_AMOUNT', 'index'],
    rgSafeDoorLock:                ['gerneral', 'System', 'SAFE_DOOR_LOCK', 'index'],
    rgSafePlcIO:                   ['gerneral', 'System', 'SafePlcIO', 'index'],
    rgScanner_AOI:                 ['gerneral', 'System', 'Scanner_AOI', 'index'],
    rgShuttleCrossSensor:          ['gerneral', 'System', 'CROSS_SENSOR_INSTALL', 'index'],
    rgShuttleFloating:             ['gerneral', '2D_BarCode', 'SHT_FLOATING_CHK', 'index'],
    rgShuttleFloodgate:            ['gerneral', 'System', 'SHUTTLE_FLOODGATE', 'index'],
    rgShuttleSensor:               ['gerneral', 'System', 'SHUTTLE_SENSOR_TYPE', 'index'],
    rgShuttleVibration:            ['gerneral', 'System', 'ShuttleVibration', 'index'],
    rgShuttleZType:                ['gerneral', 'System', 'SHUTTLE_Z_TYPE', 'index'],
    rgSocketClamp:                 ['gerneral', 'System', 'INSTALL_SOCKET_CLAMP', 'index'],
    rgSocketSen:                   ['gerneral', 'System', 'USE_SOCKET_SENSOR', 'index'],
    rgTTLCard:                     ['gerneral', 'System', 'TTL_CARD_TYPE', 'index'],
    rgTTLUseAddress:               ['gerneral', 'System', 'TTL_CARD_USE_ADDRESS', 'index'],
    rgTopScanner_AOI:              ['gerneral', 'System', 'Top_Scanner_AOI', 'index'],
    rgTrayArmMode:                 ['gerneral', 'System', 'TRAY_ARM_MODE', 'index'],
    rgTrayMapping:                 ['gerneral', 'System', 'USE_TRAY_MAPPING', 'index'],
    rgTrayMappingGrabImage:        ['gerneral', 'System', 'TRAY_MAPPING_GRAB', 'index'],
    rgTrayRobot:                   ['gerneral', 'System', 'USE_TRAY_ROBOT', 'index'],
    rgTrayVibration:               ['gerneral', 'System', 'TRAY_VIBRATION', 'index'],
    rgTriTempMachine:              ['gerneral', 'System', 'Tri_Temp_Machine', 'index'],
    rgUse4DUT:                     ['gerneral', 'System', 'SocketBasedAdd4Temp', 'index'],
    rgUseOutSht:                   ['gerneral', 'System', 'USE_OUT_SHT_MOT', 'index'],
    rgUsePulseType:                ['gerneral', 'System', 'USE_PULSE_TYPE', 'index'],
    rgUseSensor_9046_DB:           ['gerneral', 'System', 'USE_46_SENSOR_DB', 'index'],
    rgUseSucker_9046_DB:           ['gerneral', 'System', 'USE_46_SUCKER_DB', 'index'],
    rgVacuUnitType:                ['gerneral', 'System', 'VacuUnitType', 'index'],
    rgVibrationCommuncation:       ['gerneral', 'Vibration', 'VibrationCommunication', 'index'],
    rgWeightCali:                  ['gerneral', 'System', 'WEIGHT_CALIBRATION', 'index'],
    rg_ControlPanelMode:           ['gerneral', 'System', 'ControlPanelMode', 'index'],
    rg_IndexDoorHeater:            ['gerneral', 'System', 'IndexDoorHeater', 'index'],
  },
  optional: {
  },
  // 存檔鈕依據：golden HandlerSys.cpp:1121 SaveBtnClick -> SaveSystemSet()；:1127 LoadBtnClick -> LoaderSystemSet()
  saveBtn: 'SaveBtn',
  reloadBtn: 'LoadBtn',
  pending: {
  },
  kb: {
    ed24VMonitorPulseCount:      ['INTEGER', 0, true, 5000, 1],
    edATCSystemPort:             ['PORT', 0, false, 0, 0],
    edATCSystemUseHeat:          ['INTEGER', 0, true, 32, 4],
    edCognexSystemCCD:           ['INTEGER', 0, true, 4, 2],
    edGroundMan_AlarmOhm:        ['INTEGER', 0, true, 10, 1],
    edHotGunFlow_DevNo:          ['INTEGER', 0, true, 64, 0],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1301 (range was dropped by gen_wire.py:309-315)
    edHotGunFlow_Gun1_ChannelNo: ['INTEGER', 0, true, 3, 0],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1296 (range was dropped by gen_wire.py:309-315)
    edHotGunFlow_Gun2_ChannelNo: ['INTEGER', 0, true, 3, 0],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1296 (range was dropped by gen_wire.py:309-315)
    edHotGunFlow_LineNo:         ['INTEGER', 0, true, 3, 0],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1296 (range was dropped by gen_wire.py:309-315)
    edIONPulseCount:             ['INTEGER', 0, true, 100000, 3000],
    edMaxKpa:                    ['INTEGER', 0, true, 400, 950],
    edMaxMpaFB:                  ['DOUBLE', 3, true, 0.0, 6.0],
    edMinMpa:                    ['DOUBLE', 3, true, -1.0, 10.0],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1280 (range was dropped by gen_wire.py:309-315)
    edtBaseMaxTemp:              ['INTEGER', 0, true, 120.0, 20.0],
    edtCustomerCode:             ['INTEGER', 0, true, 999, 0],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1265 (range was dropped by gen_wire.py:309-315)
    edtHPLimit:                  ['INTEGER', 0, true, 80000, 4000],
    edtIndexMaxTemp:             ['INTEGER', 0, true, 120.0, 20.0],
    edtMaxXPitch:                ['INTEGER', 0, true, 3000, 16000],
    edtMaxYPitch:                ['INTEGER', 0, true, 80000, 4000],
    edtMinMpaFB:                 ['DOUBLE', 3, true, 0.0, 6.0],
    edtMinXPitch:                ['INTEGER', 0, true, 1100, 4000],
    edtMinYPitch:                ['INTEGER', 0, true, 6000, 1500],
    edtOutShtMaxTemp:            ['INTEGER', 0, true, 120.0, 20.0],
    edtOutSortXPitchMax:         ['INTEGER', 0, true, 3000, 16000],
    edtOutSortXPitchMin:         ['INTEGER', 0, true, 1100, 4000],
    edtTriTempTotalCh:           ['INTEGER', 0, true, 40, 4],
    edtTriTemperature_MaxDegree: ['INTEGER', 0, true, 175.0, 35.0],
    edtTriTemperature_MinDegree: ['INTEGER', 0, true, 35.0, -55.0],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1354 (range was dropped by gen_wire.py:309-315)
    edtUserDefMaxContactHeight:  ['DOUBLE', 2, true, -100.00, -160.00],   // AI(W906-QFB) 20261002: golden HandlerSys.cpp:1141 (range was dropped by gen_wire.py:309-315)
    edtUserDefineIndexZSafePos:  ['INTEGER', 2, true, 200, 800],
  }
});
