// test_st02_advmoterr_text.cpp
//
// AI(W906-W142) 20261007 (St02-E): standalone check of the AdvMotErr lookup
// generated by gen_advmoterr.py from EtherCAT/vendor/AdvMotErr.h (read-only).
// Build: g++ -std=c++17 -Wall -Wextra -O0 -o t.exe test_st02_advmoterr_text.cpp AdvMotErrText_St02.cpp
// Prints PASS/FAIL lines; returns non-zero when any check fails.

#include "EtherCAT/AdvMotErrText_St02.h"

#include <cstdio>
#include <cstring>
#include <string>

namespace {

int g_fail = 0;
int g_pass = 0;

// Count of distinct numeric values gen_advmoterr.py reported for AdvMotErr.h
// (764 #define lines, 763 numeric, 4 values shared with a category base).
const std::size_t kExpectedDistinct = 759;

void Check(bool ok, const char* what)
{
    std::printf("%s  %s\n", ok ? "PASS" : "FAIL", what);
    if (ok)
        ++g_pass;
    else
        ++g_fail;
}

bool StrEq(const char* a, const char* b)
{
    return a && b && std::strcmp(a, b) == 0;
}

void CheckCode(unsigned long code, const char* name, const char* text)
{
    using namespace ht9045;
    char what[160];
    std::snprintf(what, sizeof(what), "0x%08lX name == %s", code, name);
    Check(StrEq(AdvMotErrName(code), name), what);
    std::snprintf(what, sizeof(what), "0x%08lX text == \"%s\"", code, text);
    Check(AdvMotErrText(code) == text, what);
    char hex[16];
    std::snprintf(hex, sizeof(hex), "0x%08lX", code);
    const std::string want = std::string(hex) + " " + name + " (" + text + ")";
    std::snprintf(what, sizeof(what), "0x%08lX describe == \"%s\"", code, want.c_str());
    Check(AdvMotErrDescribe(code) == want, what);
}

} // namespace

int main()
{
    using namespace ht9045;

    // 1) the machine owner's examples
    CheckCode(0x8000002DUL, "InvalidAxDistance", "invalid axis distance");
    CheckCode(0x80000011UL, "InvalidAxParVelLow", "invalid axis parameter: velocity low");
    CheckCode(0x80000012UL, "InvalidAxParVelHigh", "invalid axis parameter: velocity high");
    CheckCode(0x80000013UL, "InvalidAxParAcc", "invalid axis parameter: acceleration");
    CheckCode(0x80000014UL, "InvalidAxParDec", "invalid axis parameter: deceleration");

    // 2) SUCCESS (0) is a define in the header -> name "SUCCESS"
    CheckCode(0x00000000UL, "SUCCESS", "success");

    // 3) unknown code -> nullptr / "" / "(unknown AdvMotErr code)"
    const unsigned long unknown = 0x80000FFFUL;
    Check(AdvMotErrName(unknown) == nullptr, "0x80000FFF name == nullptr");
    Check(AdvMotErrText(unknown).empty(), "0x80000FFF text == \"\"");
    Check(AdvMotErrDescribe(unknown) == "0x80000FFF (unknown AdvMotErr code)",
          "0x80000FFF describe == \"0x80000FFF (unknown AdvMotErr code)\"");
    Check(AdvMotErrName(0x7FFFFFFFUL) == nullptr, "0x7FFFFFFF name == nullptr");

    // 4) a value shared with a category base resolves to the real code
    Check(StrEq(AdvMotErrName(0x80000000UL), "InvalidDevNumber"),
          "0x80000000 name == InvalidDevNumber (alias FuncError)");

    // 5) table strictly sorted, no duplicate codes, size == generator count
    std::size_t n = 0;
    const AdvMotErrEntry* t = AdvMotErrTable(&n);
    bool sorted = (t != nullptr);
    std::size_t badAt = 0;
    for (std::size_t i = 1; sorted && i < n; ++i) {
        if (!(t[i - 1].code < t[i].code)) {
            sorted = false;
            badAt = i;
        }
    }
    if (!sorted)
        std::printf("      first unsorted/duplicate index %u\n", static_cast<unsigned>(badAt));
    Check(sorted, "table strictly ascending (no duplicate codes)");
    bool allNamed = true;
    for (std::size_t i = 0; i < n; ++i)
        if (!t[i].name || !*t[i].name || !t[i].text || !*t[i].text)
            allNamed = false;
    Check(allNamed, "every entry has a non-empty name and text");
    char what[96];
    std::snprintf(what, sizeof(what), "table size %u == generator distinct count %u",
                  static_cast<unsigned>(n), static_cast<unsigned>(kExpectedDistinct));
    Check(n == kExpectedDistinct && n == kAdvMotErrDistinctValues, what);

    // every entry round-trips through the lookup
    bool roundTrip = true;
    for (std::size_t i = 0; i < n; ++i)
        if (AdvMotErrName(t[i].code) != t[i].name)
            roundTrip = false;
    Check(roundTrip, "every table entry is found by binary search");

    // 6) spot checks on other bases
    //    CommError 0x80001000: the header defines no (CommError + N) codes, only the base.
    CheckCode(0x80001000UL, "CommError", "communication error");
    //    DspAxError + 0x0d
    CheckCode(0x8000510DUL, "Dsp_InvalidAxDistance", "DSP invalid axis distance");
    //    Gm_CodeError (GmError + 0x100) + 3
    CheckCode(0x81000103UL, "Gm_InvalidGCode", "G-code (GM) invalid G code");

    std::printf("\nexamples:\n");
    const unsigned long ex[] = { 0x8000002DUL, 0x80000011UL, 0x80000012UL,
                                 0x80000013UL, 0x80000014UL, 0x80001000UL,
                                 0x8000510DUL, 0x81000103UL, 0x80000FFFUL };
    for (unsigned long c : ex)
        std::printf("  %s\n", AdvMotErrDescribe(c).c_str());

    std::printf("\n%d passed, %d failed\n", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
